version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: ["flask", "run", "--host=0.0.0.0", "--port=9090"]
    ports:
      - "9090:9090"
